CREATE TABLE ecom_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_ecom_user PRIMARY KEY (id)
);

CREATE TABLE ecom_user_roles
(
    ecom_user_id BIGINT NOT NULL,
    roles_id     BIGINT NOT NULL,
    CONSTRAINT pk_ecom_user_roles PRIMARY KEY (ecom_user_id, roles_id)
);

CREATE TABLE role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE session
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT,
    token          VARCHAR(255),
    logged_in_at   TIMESTAMP WITHOUT TIME ZONE,
    logged_out_at  TIMESTAMP WITHOUT TIME ZONE,
    session_status SMALLINT,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

ALTER TABLE ecom_user
    ADD CONSTRAINT uc_ecom_user_email UNIQUE (email);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_USER FOREIGN KEY (user_id) REFERENCES ecom_user (id);

ALTER TABLE ecom_user_roles
    ADD CONSTRAINT fk_ecouserol_on_role FOREIGN KEY (roles_id) REFERENCES role (id);

ALTER TABLE ecom_user_roles
    ADD CONSTRAINT fk_ecouserol_on_user FOREIGN KEY (ecom_user_id) REFERENCES ecom_user (id);